### ISSUE TITLE
timeline / description page 기능 제작

### ISSUE THREAD

**Issue by YuSoeun** [I-Taxi/itaxi-front#175]
**Description**
- timeline page 모집하러 가기 기능 제작
- 전화, 문자, message 페이지 이동

**Todo**
- [x] timeline page 모집하러 가기 기능
- [x] 상세 페이지 전화, 문자
- [x] 상세 페이지 페이지 이동 (톡방으로 이동)
- [x] 테스트
