### ISSUE TITLE
settingScreen UI 수정(MyInfoScreen 제외)

### ISSUE THREAD

**Issue by 2021jian** [I-Taxi/itaxi-front#210]
**Description**
- settingScreen 폰트 수정
- settingScreen 간격 수정
- setting Screen 색상 수정

**Todo**
- [x] settingScreen 폰트 수정
- [x] settingScreen 간격 수정
- [x] setting Screen 색상 수정
