### ISSUE TITLE
로그인, onboarding, 방만들기 버튼, 네비바 패딩

### ISSUE THREAD

**Issue by 2021jian** [I-Taxi/itaxi-front#235]
**Description**
- 로그인 텍스트 수정
- onboarding 해상도 밝기 수정
- 짤리는 방지
- 출발지, 도착지 버튼 클릭시 오류 null 처리

**Todo**
- [x] 로그인 텍스트 수정
- [x] onboarding 해상도 밝기 수정
- [x] 출발지, 도착지 버튼 클릭시 오류 null 처리
- [x] 짤리는 방지

**ETC**
- 기타사항사항
