### ISSUE TITLE
로그인, 회원가입 page 오류 수정

### ISSUE THREAD

**Issue by 2021jian** [I-Taxi/itaxi-front#244]
**Description**
- 자동 로그인 오류 수정
- 회원가입 시 비밀번호 문자 형식 수정
- 이용 약관, 개인정보처리 방침 간격 수정

**Todo**
- [x] 자동 로그인 오류 수정
- [x] 회원가입 시 비밀번호 문자 형식 수정
- [x] 이용 약관, 개인정보처리 방침 간격 수정
