### ISSUE TITLE
채팅 오류 피드백 수정

### ISSUE THREAD

**Issue by hhjj0506** [I-Taxi/itaxi-front#246]
**Description**
- 채팅 오류 피드백 수정

**Todo**
- [x] #264
- [x] 방 제목 수정 버튼 삭제
- [x] 새 메세지 버튼 깨짐
- [x] 방제 날짜 표시 방식 변경
- [x] 알람 제목 형식 변경
- [x] 채팅방 방장 맞게 표시
- [x] 방 나가기 후 다시 들어오기 불가
- [x] 방 만들고 나가기 안됨
- [x] 나가기 할때 null check error
- [x] 날짜 업데이트 오류
- [x] 입장 시 첫 채팅부터 표시
