### ISSUE TITLE
UI 버그 및 오류 수정 + 추가 개발

### ISSUE THREAD

**Issue by 2021jian** [I-Taxi/itaxi-front#87]
**Description**
- 아이폰 UI overflow 수정
- 남은 항목들 개발

**Todo**
- [x] 출발지, 도착지 입력 시 해당 장소로 text 변경
- [ ] 티켓 내에서 아이폰 간격 오류
- [ ] 탑승 버튼 클릭 시 soontimeline으로 정보 이동확인
- [ ] I-TAXI 2기 개발자 이스터에그 작성
- [ ] 공지사항 page 구현
- [ ] 회원 탈퇴하기 클릭 시 조건에 따라 dialog 표시 세분화
- [ ] 휴대폰 번호 재설정 page 연결(1기꺼로)
- [ ] 비밀번호 재설정 page 제작

**Comment by 2021jian** [comment]
dev 통합으로 인해 issue 재생성해야 해서 close
