### ISSUE TITLE
타임 라인 UI 수정

### ISSUE THREAD

**Issue by YuSoeun** [I-Taxi/itaxi-front#89]
**Description**
- 타임 라인

**Todo**
- [x] 타임 라인 아무것도 없을 시 component들 가운데 정렬
- [x] 배경 색상 변경 (onBackground color 변경)
- [x] 타임라인 상세 페이지 제작
- [x] 기존 페이지와 상세 페이지 연결
